/*
 * File: app/view/Prey.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.view.Prey', {
    extend: 'Ext.Panel',
    alias: 'widget.Prey',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        cls: 'my-buttons',
                        id: 'addContact',
                        iconCls: 'icon-add-contact',
                        iconMask: true,
                        text: 'Add Prey'
                    }
                ]
            },
            {
                xtype: 'list',
                cls: 'x-list-normal',
                id: 'myContactDataView',
                itemId: 'myContactDataView',
                disableSelection: true,
                itemTpl: [
                    '<div>',
                    '<div style="margin-right:.5em;float:left;width:1.1em;height:1.1em;background-color:orange;-webkit-mask-image: url(\'resources/images/user_business.png\');-webkit-mask-size: 1.1em;"></div>',
                    '',
                    '{name}',
                    '<b class=\'money-label\' style=\'float: right;color:red;\'>',
                    '{[(values.balance<0)?\'-\':\'\']}${[Math.abs(values.balance).toFixed(2)]}',
                    '</b>',
                    '<br>',
                    '</div>'
                ],
                store: 'People'
            }
        ]
    }

});